import Foundation
import SeerCore

#if canImport(CryptoKit)
import CryptoKit
#elseif canImport(Crypto)
import Crypto
#endif

// Dev-machine tool that turns plaintext credentials into `secrets.enc` plus a
// generated Swift file holding the split key seed.
//
//   swift run seer-secrets encrypt \
//       --salt com.yourteam.seer \
//       --in Secrets.env \
//       --out Seer/Resources/secrets.enc \
//       --swift-out Seer/Generated/SecretsSeed.swift
//
// Neither the input file nor the output blob is committed — both are gitignored. The
// generated Swift file *is* committed: on its own it decrypts nothing.
//
// See docs/SECRETS.md for where each piece goes, and for what this does and does not
// protect against.

struct ToolError: Error, CustomStringConvertible {
    let description: String
    init(_ description: String) { self.description = description }
}

func parseArguments(_ arguments: [String]) -> [String: String] {
    var parsed: [String: String] = [:]
    var index = 0
    while index < arguments.count {
        let argument = arguments[index]
        if argument.hasPrefix("--"), index + 1 < arguments.count {
            parsed[String(argument.dropFirst(2))] = arguments[index + 1]
            index += 2
        } else {
            index += 1
        }
    }
    return parsed
}

/// Reads `KEY=value` lines. Blank lines and `#` comments ignored; values may contain `=`.
func parseEnvFile(_ contents: String) -> [String: String] {
    var values: [String: String] = [:]
    for line in contents.split(separator: "\n", omittingEmptySubsequences: true) {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty, !trimmed.hasPrefix("#"),
              let separator = trimmed.firstIndex(of: "=") else { continue }
        let key = String(trimmed[..<separator]).trimmingCharacters(in: .whitespaces)
        var value = String(trimmed[trimmed.index(after: separator)...]).trimmingCharacters(in: .whitespaces)
        // Tolerate quoted values.
        if value.count >= 2, (value.hasPrefix("\"") && value.hasSuffix("\""))
            || (value.hasPrefix("'") && value.hasSuffix("'")) {
            value = String(value.dropFirst().dropLast())
        }
        guard !key.isEmpty, !value.isEmpty else { continue }
        values[key] = value
    }
    return values
}

extension Array {
    func chunked(into size: Int) -> [[Element]] {
        stride(from: 0, to: count, by: size).map { Array(self[$0..<Swift.min($0 + size, count)]) }
    }
}

func swiftSource(maskA: [UInt8], maskB: [UInt8], salt: String) -> String {
    func literal(_ bytes: [UInt8]) -> String {
        bytes.map { String(format: "0x%02x", $0) }
            .chunked(into: 12)
            .map { "        " + $0.joined(separator: ", ") }
            .joined(separator: ",\n")
    }

    return """
    // Generated by `swift run seer-secrets encrypt`. Do not edit.
    //
    // These two halves XOR together into the seed that derives the key for
    // `secrets.enc`. Neither half is a key on its own, and neither appears verbatim in
    // the built binary's data section.
    //
    // Committing this file is intentional and safe on its own: without `secrets.enc`
    // it decrypts nothing. It is obfuscation, not secrecy — see docs/SECRETS.md.

    import Foundation
    import SeerCore

    enum GeneratedSecretsSeed {
        static let salt = "\(salt)"

        private static let maskA: [UInt8] = [
    \(literal(maskA))
        ]

        private static let maskB: [UInt8] = [
    \(literal(maskB))
        ]

        static var seed: Data { SecretsKeySeed.reassemble(maskA, maskB) }
    }
    """
}

// MARK: - main

let arguments = Array(CommandLine.arguments.dropFirst())

guard let command = arguments.first, command == "encrypt" else {
    FileHandle.standardError.write(Data("""
    usage: seer-secrets encrypt --salt <bundle-id> --in <env-file> --out <secrets.enc> \
    [--swift-out <SecretsSeed.swift>]

      --salt       Bundle identifier the blob is bound to. Must match the value passed
                   to EncryptedSecretsBundle at runtime (its default is the bundle id).
      --in         KEY=value file with the plaintext credentials. Never commit it.
      --out        Where to write the encrypted blob. Add it to the app target's
                   Copy Bundle Resources phase. Never commit it.
      --swift-out  Where to write the generated key-seed source. Commit this one.

    """.utf8))
    exit(2)
}

do {
    let options = parseArguments(Array(arguments.dropFirst()))

    guard let salt = options["salt"] else { throw ToolError("missing --salt") }
    guard let inputPath = options["in"] else { throw ToolError("missing --in") }
    guard let outputPath = options["out"] else { throw ToolError("missing --out") }

    let contents = try String(contentsOfFile: inputPath, encoding: .utf8)
    let values = parseEnvFile(contents)
    guard !values.isEmpty else {
        throw ToolError("no KEY=value pairs found in \(inputPath)")
    }

    // Fresh 32-byte seed on every run, split into two random-looking halves.
    var seed = [UInt8](repeating: 0, count: 32)
    var maskA = [UInt8](repeating: 0, count: 32)
    for index in 0..<32 {
        seed[index] = UInt8.random(in: 0...255)
        maskA[index] = UInt8.random(in: 0...255)
    }
    let maskB = zip(seed, maskA).map { $0 ^ $1 }

    let blob = try EncryptedSecretsBundle.seal(values, keySeed: Data(seed), salt: salt)

    let outputURL = URL(fileURLWithPath: outputPath)
    try FileManager.default.createDirectory(
        at: outputURL.deletingLastPathComponent(), withIntermediateDirectories: true
    )
    try blob.write(to: outputURL)

    if let swiftOutPath = options["swift-out"] {
        let swiftURL = URL(fileURLWithPath: swiftOutPath)
        try FileManager.default.createDirectory(
            at: swiftURL.deletingLastPathComponent(), withIntermediateDirectories: true
        )
        try swiftSource(maskA: maskA, maskB: maskB, salt: salt)
            .write(to: swiftURL, atomically: true, encoding: .utf8)
        print("wrote \(swiftOutPath) (commit this)")
    }

    // Prove the round trip before declaring success — a blob that can't be opened would
    // otherwise only surface at app launch.
    let verification = EncryptedSecretsBundle(
        ciphertext: blob, keySeed: SecretsKeySeed.reassemble(maskA, maskB), salt: salt
    )
    let recovered = try verification.decryptAll()
    guard recovered == values else { throw ToolError("round-trip verification failed") }

    print("wrote \(outputPath) — \(values.count) secret(s): \(values.keys.sorted().joined(separator: ", "))")
    print("verified: blob decrypts with the generated seed")
    print("")
    print("Do not commit \(inputPath) or \(outputPath). Both are gitignored.")
} catch {
    FileHandle.standardError.write(Data("error: \(error)\n".utf8))
    exit(1)
}
